export const mockCompanions = [
  {
    id: "comp-001",
    name: "Aarav Sharma",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    rating: 4.9,
    reviews: 128,
    activities: ["Coffee", "Movies", "Study"],
    hourlyRate: 499,
    languages: ["Hindi", "English"],
    bio: "Easy-going and friendly companion who enjoys meaningful conversations, movies and coffee.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-002",
    name: "Priya Verma",
    age: 23,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    rating: 4.8,
    reviews: 96,
    activities: ["Coffee", "Chat", "Shopping"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Friendly and social companion who loves exploring cafes and having good conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-003",
    name: "Rohan Mehta",
    age: 26,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    rating: 4.7,
    reviews: 74,
    activities: ["Gym", "Movies", "Study"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Fitness enthusiast and movie lover. Available for gym sessions, movies and study sessions.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-004",
    name: "Ananya Gupta",
    age: 22,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    rating: 4.9,
    reviews: 142,
    activities: ["Coffee", "Chat", "Movies"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Warm and outgoing companion who enjoys cafes, movies and interesting conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-005",
    name: "Kabir Malhotra",
    age: 27,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    rating: 4.6,
    reviews: 63,
    activities: ["Gym", "Coffee", "Events"],
    hourlyRate: 499,
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Social and energetic companion who enjoys fitness and attending events.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-006",
    name: "Meera Joshi",
    age: 25,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    rating: 4.8,
    reviews: 111,
    activities: ["Study", "Coffee", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Calm and friendly companion who enjoys study sessions and relaxed conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-007",
    name: "Aditya Singh",
    age: 25,
    location: "Jabalpur",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    rating: 4.7,
    reviews: 82,
    activities: ["Movies", "Coffee", "Gaming"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Movie and gaming enthusiast who enjoys spending time in relaxed social settings.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-008",
    name: "Kavya Patel",
    age: 24,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    rating: 4.9,
    reviews: 157,
    activities: ["Shopping", "Coffee", "Events"],
    hourlyRate: 649,
    languages: ["Hindi", "English", "Gujarati"],
    bio: "Cheerful companion who loves shopping, cafes and social events.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-009",
    name: "Vihaan Kapoor",
    age: 28,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    rating: 4.6,
    reviews: 58,
    activities: ["Business", "Coffee", "Chat"],
    hourlyRate: 699,
    languages: ["Hindi", "English"],
    bio: "Professional and conversational companion for networking and coffee meetups.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-010",
    name: "Isha Agarwal",
    age: 23,
    location: "Ujjain",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    rating: 4.8,
    reviews: 91,
    activities: ["Movies", "Chat", "Coffee"],
    hourlyRate: 499,
    languages: ["Hindi", "English"],
    bio: "Friendly companion who enjoys movies, conversations and discovering new cafes.",
    verified: true,
    availability: true,
  },

  {
    id: "comp-011",
    name: "Arjun Rao",
    age: 26,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    rating: 4.7,
    reviews: 76,
    activities: ["Gym", "Running", "Coffee"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Fitness-focused companion who enjoys outdoor activities and coffee.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-012",
    name: "Sanya Kapoor",
    age: 24,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    rating: 4.9,
    reviews: 134,
    activities: ["Coffee", "Shopping", "Chat"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Outgoing companion who enjoys shopping trips and casual conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-013",
    name: "Dev Mishra",
    age: 25,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    rating: 4.8,
    reviews: 103,
    activities: ["Study", "Gaming", "Movies"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Tech enthusiast who enjoys gaming, movies and productive study sessions.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-014",
    name: "Riya Saxena",
    age: 22,
    location: "Jabalpur",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    rating: 4.6,
    reviews: 57,
    activities: ["Study", "Coffee", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Student-friendly companion for study sessions and casual conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-015",
    name: "Manav Jain",
    age: 27,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    rating: 4.7,
    reviews: 88,
    activities: ["Events", "Movies", "Coffee"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Social companion who enjoys events, movies and exploring the city.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-016",
    name: "Nisha Sharma",
    age: 25,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    rating: 4.9,
    reviews: 121,
    activities: ["Coffee", "Movies", "Events"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Social and positive companion who enjoys cafes and local events.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-017",
    name: "Yash Thakur",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    rating: 4.5,
    reviews: 49,
    activities: ["Gaming", "Movies", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Gaming and movie enthusiast with a relaxed and friendly personality.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-018",
    name: "Tanya Mehta",
    age: 23,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    rating: 4.8,
    reviews: 102,
    activities: ["Shopping", "Coffee", "Movies"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Friendly companion for shopping, movies and cafe visits.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-019",
    name: "Ritvik Verma",
    age: 26,
    location: "Ujjain",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    rating: 4.7,
    reviews: 67,
    activities: ["Travel", "Coffee", "Photography"],
    hourlyRate: 649,
    languages: ["Hindi", "English"],
    bio: "Photography enthusiast who enjoys exploring new places and cafes.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-020",
    name: "Simran Kaur",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    rating: 4.9,
    reviews: 145,
    activities: ["Coffee", "Chat", "Events"],
    hourlyRate: 599,
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Warm and social companion who enjoys conversations and city events.",
    verified: true,
    availability: true,
  },

  {
    id: "comp-021",
    name: "Ayaan Khan",
    age: 25,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    rating: 4.8,
    reviews: 94,
    activities: ["Gym", "Coffee", "Running"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Active companion who enjoys fitness, running and coffee meetups.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-022",
    name: "Shreya Gupta",
    age: 22,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    rating: 4.7,
    reviews: 71,
    activities: ["Study", "Coffee", "Movies"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Calm companion for study sessions, coffee and movies.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-023",
    name: "Karan Joshi",
    age: 27,
    location: "Jabalpur",
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    rating: 4.6,
    reviews: 61,
    activities: ["Movies", "Gaming", "Chat"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Easy-going companion who enjoys gaming, movies and conversations.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-024",
    name: "Aditi Rao",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    rating: 4.9,
    reviews: 119,
    activities: ["Coffee", "Shopping", "Chat"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Friendly and cheerful companion who enjoys cafes and shopping.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-025",
    name: "Raghav Soni",
    age: 28,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    rating: 4.8,
    reviews: 87,
    activities: ["Business", "Coffee", "Events"],
    hourlyRate: 699,
    languages: ["Hindi", "English"],
    bio: "Professional companion for networking, coffee and business events.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-026",
    name: "Neha Kapoor",
    age: 23,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    rating: 4.7,
    reviews: 78,
    activities: ["Movies", "Coffee", "Chat"],
    hourlyRate: 499,
    languages: ["Hindi", "English"],
    bio: "Movie lover and friendly conversational companion.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-027",
    name: "Samar Singh",
    age: 26,
    location: "Ujjain",
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    rating: 4.5,
    reviews: 43,
    activities: ["Travel", "Photography", "Coffee"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Travel and photography enthusiast who enjoys discovering new places.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-028",
    name: "Pooja Verma",
    age: 25,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    rating: 4.8,
    reviews: 109,
    activities: ["Shopping", "Events", "Coffee"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Social companion who enjoys events, shopping and coffee.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-029",
    name: "Harsh Agarwal",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    rating: 4.9,
    reviews: 132,
    activities: ["Study", "Gaming", "Coffee"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Tech and gaming enthusiast who also enjoys productive study sessions.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-030",
    name: "Muskan Jain",
    age: 22,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    rating: 4.6,
    reviews: 55,
    activities: ["Chat", "Coffee", "Movies"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Friendly companion who enjoys relaxed conversations and movies.",
    verified: true,
    availability: false,
  },

  {
    id: "comp-031",
    name: "Dhruv Patel",
    age: 27,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    rating: 4.8,
    reviews: 97,
    activities: ["Gym", "Running", "Coffee"],
    hourlyRate: 499,
    languages: ["Hindi", "English", "Gujarati"],
    bio: "Fitness enthusiast who enjoys running and outdoor activities.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-032",
    name: "Ritika Sharma",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    rating: 4.9,
    reviews: 126,
    activities: ["Coffee", "Movies", "Shopping"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Outgoing companion who loves cafes, movies and shopping.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-033",
    name: "Nikhil Mishra",
    age: 25,
    location: "Jabalpur",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    rating: 4.7,
    reviews: 73,
    activities: ["Study", "Coffee", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Study-friendly companion who enjoys focused sessions and conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-034",
    name: "Kriti Malhotra",
    age: 26,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    rating: 4.8,
    reviews: 88,
    activities: ["Events", "Coffee", "Movies"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Social and friendly companion for events, movies and cafe visits.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-035",
    name: "Siddharth Roy",
    age: 28,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    rating: 4.6,
    reviews: 64,
    activities: ["Business", "Coffee", "Chat"],
    hourlyRate: 699,
    languages: ["Hindi", "English"],
    bio: "Professional companion who enjoys networking and meaningful conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-036",
    name: "Rhea Kapoor",
    age: 23,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    rating: 4.9,
    reviews: 138,
    activities: ["Coffee", "Chat", "Shopping"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Friendly companion who enjoys conversations, cafes and shopping.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-037",
    name: "Ansh Verma",
    age: 24,
    location: "Ujjain",
    avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    rating: 4.7,
    reviews: 81,
    activities: ["Movies", "Gaming", "Coffee"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Movie and gaming enthusiast with a relaxed personality.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-038",
    name: "Sneha Gupta",
    age: 25,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/38.jpg",
    rating: 4.8,
    reviews: 112,
    activities: ["Study", "Coffee", "Movies"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Calm companion for study sessions, coffee and movies.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-039",
    name: "Aryan Saxena",
    age: 26,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    rating: 4.9,
    reviews: 151,
    activities: ["Gym", "Movies", "Coffee"],
    hourlyRate: 549,
    languages: ["Hindi", "English"],
    bio: "Active and social companion who enjoys fitness and movies.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-040",
    name: "Manya Joshi",
    age: 22,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/40.jpg",
    rating: 4.7,
    reviews: 69,
    activities: ["Chat", "Coffee", "Study"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Friendly companion for conversations, study and coffee.",
    verified: true,
    availability: true,
  },

  {
    id: "comp-041",
    name: "Reyansh Mehta",
    age: 27,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    rating: 4.8,
    reviews: 104,
    activities: ["Travel", "Photography", "Coffee"],
    hourlyRate: 649,
    languages: ["Hindi", "English"],
    bio: "Travel enthusiast who enjoys photography and exploring new places.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-042",
    name: "Avni Sharma",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/42.jpg",
    rating: 4.9,
    reviews: 143,
    activities: ["Coffee", "Events", "Movies"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Social companion who enjoys local events, cafes and movies.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-043",
    name: "Rudra Singh",
    age: 25,
    location: "Jabalpur",
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    rating: 4.6,
    reviews: 52,
    activities: ["Gaming", "Movies", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Gaming enthusiast who enjoys movies and casual conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-044",
    name: "Diya Patel",
    age: 23,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    rating: 4.8,
    reviews: 118,
    activities: ["Shopping", "Coffee", "Events"],
    hourlyRate: 549,
    languages: ["Hindi", "English", "Gujarati"],
    bio: "Cheerful companion who enjoys shopping, cafes and events.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-045",
    name: "Aman Khan",
    age: 28,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    rating: 4.7,
    reviews: 86,
    activities: ["Business", "Coffee", "Events"],
    hourlyRate: 699,
    languages: ["Hindi", "English"],
    bio: "Professional companion for networking and social events.",
    verified: true,
    availability: false,
  },
  {
    id: "comp-046",
    name: "Ishita Rao",
    age: 24,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/46.jpg",
    rating: 4.9,
    reviews: 127,
    activities: ["Coffee", "Chat", "Movies"],
    hourlyRate: 499,
    languages: ["Hindi", "English"],
    bio: "Friendly and conversational companion who enjoys movies and cafes.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-047",
    name: "Lakshya Gupta",
    age: 26,
    location: "Ujjain",
    avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    rating: 4.8,
    reviews: 93,
    activities: ["Gym", "Running", "Coffee"],
    hourlyRate: 449,
    languages: ["Hindi", "English"],
    bio: "Fitness enthusiast who enjoys running and casual coffee meetups.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-048",
    name: "Aarohi Verma",
    age: 22,
    location: "Indore",
    avatar: "https://randomuser.me/api/portraits/women/48.jpg",
    rating: 4.7,
    reviews: 75,
    activities: ["Study", "Coffee", "Chat"],
    hourlyRate: 399,
    languages: ["Hindi", "English"],
    bio: "Student-friendly companion for study sessions and conversations.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-049",
    name: "Vedant Sharma",
    age: 27,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/men/49.jpg",
    rating: 4.9,
    reviews: 139,
    activities: ["Movies", "Coffee", "Gaming"],
    hourlyRate: 499,
    languages: ["Hindi", "English"],
    bio: "Easy-going companion who enjoys movies, gaming and coffee.",
    verified: true,
    availability: true,
  },
  {
    id: "comp-050",
    name: "Kiara Mehta",
    age: 25,
    location: "Bhopal",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
    rating: 4.8,
    reviews: 116,
    activities: ["Coffee", "Shopping", "Events"],
    hourlyRate: 599,
    languages: ["Hindi", "English"],
    bio: "Social companion who enjoys cafes, shopping and city events.",
    verified: true,
    availability: true,
  },
];